### ISSUE TITLE
documentation 

### ISSUE THREAD

**Issue by robertoostenveld** [things4u/things4u.github.io#2]
On the page http://things4u.github.io/HardwareGuide/Single-Channel-Gway/ESP-gateway-v4.html the text on "connections for the bare board" is present twice. 

I suggest that the hardware is ordered like
1) bare board
2) ComResult version
3) Hallard version

Perhaps you also want to include this version http://www.ebay.com/itm/LoRaGo-Dock-Single-Channel-LoRaWAN-Gateway-Based-on-SX1276-and-ESP8266/122721131735

PS I considered a pull request, but realise that the html seems to be written with an html editor. Let me know if you would prefer a PR with the proposed changes.

**Comment by platenspeler** [comment]
You are right. Thanks!
I removed the bare board section. For the price of Hallard I expect nobody to use it anymore.

Maarten
